name: Trying to upload and deploy to Heroku

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: deploy heroku
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "java-project-school-ehran"
                heroku_email: "r0661627@student.thomasmore.be"
                
    pester-test:
        name: pester-test
        runs-on: ubuntu-latest
        steps:
            - name: Checking out repository code
              uses: actions/checkout@v2
            - name: perfom test from command-line
              shell: pwsh
              run: Test-Path pom.xml | Should -Be $true
            - name: test from file
              shell: pwsh
              run: Invoke-Pester Unit.Tests.ps1 -Passthru
            
        
